---

- name: ensure kafka directories
  file: path="{{ item }}" state="directory" mode="0755"
  with_items:
    - "{{ kafka_config_dir }}"
    - "{{ kafka_data_dir }}"
    - "{{ kafka_cert_dir }}"

- name: ensure server.properties file.
  template: src="server.properties.j2" dest="{{ kafka_config_dir }}/server.properties" owner=root group=root mode=0766

- name: copy truststore onboard
  copy:
    src: "server.truststore.jks"
    dest: "{{ kafka_cert_dir }}/server.truststore.jks"

- name: copy keystore onboard
  copy:
    src: "{{ kafka_keystore_name }}"
    dest: "{{ kafka_cert_dir }}/server.keystore.jks"

- name: Echo hostname
  debug:
    msg: "{{ ansible_hostname }}"

- name: Echo retention time
  debug: 
    msg: "{{ kafka_retention_ms | default(-1) }}"

- debug:
    msg: "hostname: {{ ansible_hostname }} {{ kafka_hostname_fqdn }} {{ kafka_hostname }}"

- name: Start Kafka docker container
  docker_container:
    image: "bjarteb/kafka:{{ kafka_version }}"
    name: "kafka"
    state: started
    restart: no
    restart_policy: always
    etc_hosts: "{{ etc_hosts | default({}) }}"
    network_mode: host
    ports:
      - "9092:9092"
      - "9093:9093"
    command: /kafka/bin/kafka-server-start.sh /kafka/config/server.properties --override broker.id=-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ kafka_data_dir }}:/data"
      - "{{ kafka_config_dir }}/server.properties:/kafka/config/server.properties:ro"
      - "{{ kafka_cert_dir }}:/var/private/ssl"
  notify: kafka restarted wait

- name: Wait for kafka 9092
  wait_for:
    host: 0.0.0.0
    port: 9092

